### PR TITLE
chore: updating dependabot to support gha and cargo packages

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Comment by rajpalc7** [comment]
@wadebarnes , this is ready for review now

**Review by WadeBarnes — APPROVED** [review]
Looks good other than your code is a bit behind the main repo.

**Comment by WadeBarnes** [comment]
@rajpalc7, I'm not exactly sure what's happened here, but this PR is including two commits that already exist on the main branch, indicating some form of conflict.  If you're changes were rebased properly your change should be the only one showing.

**Comment by WadeBarnes** [comment]
Ignore the review above.  The PR to https://github.com/hyperledger/indy-shared-rs/pull/50 looks correct.

**Pull request closed without merging**
